name: Build and Push Docker Image

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]
    workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  DOCKERHUB_CACHE_IMAGE: dalvy07/weather-app-cache

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      security-events: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub (for cache)
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=sha,prefix={{branch}}-,format=short,enable={{github.event_name == 'push'}}
            type=sha,prefix=pr-{{github.event.pull_request.number}}-,format=short,enable={{github.event_name == 'pull_request'}}
            # type=sha,format=short
            # type=ref,event=branch,enable={{!is_default_branch}}
            # type=ref,event=pr
          labels: |
            org.opencontainers.image.title=Weather App
            org.opencontainers.image.description=A minimalistic weather application
            org.opencontainers.image.authors=Vladyslav Liulka <vladlulka3@gmail.com>

      - name: Build Docker image (single build)
        id: build
        uses: docker/build-push-action@v5
        with:
          context: .                    # Build context = корень репозитория
          file: build/Dockerfile        # Dockerfile в папке build/
          platforms: linux/amd64,linux/arm64  # Мультиплатформенная сборка
          secrets: |
            api_key=${{ secrets.WEATHER_API_KEY }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: |
            type=registry,ref=${{ env.DOCKERHUB_CACHE_IMAGE }}:latest
          cache-to: |
            type=registry,ref=${{ env.DOCKERHUB_CACHE_IMAGE }}:latest,mode=max
          # Ключевая оптимизация: сохраняем образ локально для тестирования
          outputs: |
            type=docker,dest=/tmp/image.tar
          sbom: true
          provenance: mode=max

      - name: Load Docker image for testing
        run: |
          echo "Loading Docker image from tar archive..."
          
          docker load --input /tmp/image.tar
          
          TEST_TAG=$(echo '${{ steps.meta.outputs.tags }}' | head -n1)
          echo "Using tag for testing: $TEST_TAG"
          echo "TEST_TAG=$TEST_TAG" >> $GITHUB_ENV
          
          echo "Image size: $(docker image inspect "$TEST_TAG" --format='{{.Size}}' | numfmt --to=iec-i --suffix=B)"
          echo "Architecture: $(docker image inspect "$TEST_TAG" --format='{{.Architecture}}')"
        # После этого шага образ доступен для всех Docker команд
        # TEST_TAG содержит имя образа для использования в тестах

      - name: Run Trivy vulnerability scanner
        id: trivy-scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.TEST_TAG }}          # Сканируем загруженный образ
          format: 'sarif'                         # Формат вывода для GitHub Security
          output: 'trivy-results.sarif'          # Файл с результатами
          severity: 'CRITICAL,HIGH'              # Сканируем критические и высокие уязвимости
          exit-code: '0'                         # Не завершаем с ошибкой, обработаем вручную
        # Trivy - популярный open source сканер уязвимостей
        # Сканирует OS пакеты, языковые зависимости, известные CVE
        # Результаты сохраняются в SARIF формате для GitHub Security

      - name: Upload Trivy scan results to GitHub Security
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'

        # Загружаем SARIF отчет в GitHub Security tab
        # if: always() гарантирует загрузку даже при ошибках сканирования
        # Результаты будут видны в Security -> Code scanning alerts

      - name: Analyze vulnerability scan results
        id: vuln-check
        run: |
          echo "Analyzing Trivy vulnerability scan results..."
          
          if [ -f "trivy-results.sarif" ]; then
            echo "Trivy SARIF file found, parsing results..."
            
            # Подсчитываем найденные уязвимости
            # Trivy уже отфильтровал по severity: 'CRITICAL,HIGH'
            total_vulnerabilities=$(jq '[.runs[].results[]] | length' trivy-results.sarif 2>/dev/null || echo "0")
            
            echo "Critical/High vulnerabilities found: $total_vulnerabilities"
            echo "vulnerability_count=$total_vulnerabilities" >> $GITHUB_OUTPUT
            
            # Принимаем решение о блокировке развертывания
            if [ "$total_vulnerabilities" -gt 0 ]; then
              echo "SECURITY BLOCK: Critical or high severity vulnerabilities detected!"
              echo "Deployment will be blocked for security reasons"
              echo "Total vulnerabilities: $total_vulnerabilities"
              
              # Показываем детали первых нескольких уязвимостей
              echo "Sample vulnerabilities:"
              jq -r '.runs[].results[0:3][] | "- " + (.ruleId // "Unknown") + ": " + .message.text' trivy-results.sarif 2>/dev/null || echo "Could not parse vulnerability details"
              
              echo "deployment_blocked=true" >> $GITHUB_OUTPUT
              exit 1
            else
              echo "SECURITY PASSED: No critical or high severity vulnerabilities found"
              echo "Image is safe for deployment"
              echo "deployment_blocked=false" >> $GITHUB_OUTPUT
            fi
          else
            echo "Trivy SARIF file not found - scan may have failed"
            echo "Proceeding with caution (scanner unavailable)"
            echo "deployment_blocked=false" >> $GITHUB_OUTPUT
          fi
        # Критическая логика безопасности:
        # - Парсим SARIF отчет и подсчитываем уязвимости
        # - Блокируем публикацию при найденных проблемах
        # - Устанавливаем флаги для условной публикации

      - name: Publish image to GitHub Container Registry
        if: |
          success() && 
          steps.vuln-check.outputs.deployment_blocked == 'false'
        run: |
          echo "Publishing security-tested image to registry..."
          echo "Publication conditions met:"
          echo "   Build successful"
          echo "   Push to main branch"  
          echo "   Security scan passed"
          echo "   No critical/high vulnerabilities"
          
          # Загружаем образ обратно и публикуем все теги
          docker load --input /tmp/image.tar
          
          echo "Publishing tags:"
          echo '${{ steps.meta.outputs.tags }}' | while IFS= read -r tag; do
            if [ -n "$tag" ]; then
              echo "  🏷️ Publishing: $tag"
              docker push "$tag"
            fi
          done
        # Публикация происходит только при выполнении всех условий:
        # - Успешная сборка
        # - Push в main ветку (не PR)
        # - Прохождение security проверок
        # Используем уже собранный и протестированный образ

      