# name: Build and Push Docker Image

# on:
#     push:
#         branches: [ main ]
#     pull_request:
#         branches: [ main ]
#     workflow_dispatch:

# env:
#   REGISTRY: ghcr.io
#   IMAGE_NAME: ${{ github.repository }}
#   DOCKERHUB_CACHE_IMAGE: dalvy07/weather-app-cache

# jobs:
#   build-and-test:
#     runs-on: ubuntu-latest
#     permissions:
#       contents: read
#       packages: write
#       security-events: write

#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v4

#       - name: Setup QEMU for multi-platform builds
#         uses: docker/setup-qemu-action@v3

#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v3

#       - name: Log in to Docker Hub (for cache)
#         uses: docker/login-action@v3
#         with:
#           username: ${{ secrets.DOCKERHUB_USERNAME }}
#           password: ${{ secrets.DOCKERHUB_TOKEN }}

#       - name: Log in to GitHub Container Registry
#         uses: docker/login-action@v3
#         with:
#           registry: ${{ env.REGISTRY }}
#           username: ${{ github.actor }}
#           password: ${{ secrets.GITHUB_TOKEN }}

#       - name: Extract metadata
#         id: meta
#         uses: docker/metadata-action@v5
#         with:
#           images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
#           tags: |
#             type=raw,value=latest,enable={{is_default_branch}}
#             type=sha,format=short
#           labels: |
#             org.opencontainers.image.title=Weather App
#             org.opencontainers.image.description=A minimalistic weather application
#             org.opencontainers.image.authors=Vladyslav Liulka <vladlulka3@gmail.com>

#       # Шаг 1: Сборка для тестирования (только amd64, docker format)
#       - name: Build Docker image for testing
#         id: build-test
#         uses: docker/build-push-action@v5
#         with:
#           context: .
#           file: build/Dockerfile
#           platforms: linux/amd64  # Только одна платформа для тестирования
#           secrets: |
#             api_key=${{ secrets.WEATHER_API_KEY }}
#           tags: test-image:latest
#           labels: ${{ steps.meta.outputs.labels }}
#           # cache-from: |
#           #   type=registry,ref=${{ env.DOCKERHUB_CACHE_IMAGE }}:latest
#           load: true  # Загружаем в локальный Docker daemon
#           sbom: true
#           provenance: mode=max
#           push: false

#       - name: Run Trivy vulnerability scanner
#         id: trivy-scan
#         uses: aquasecurity/trivy-action@master
#         with:
#           image-ref: 'test-image:latest'
#           format: 'sarif'
#           output: 'trivy-results.sarif'
#           severity: 'CRITICAL,HIGH'
#           exit-code: '0'

#       - name: Upload Trivy scan results to GitHub Security
#         uses: github/codeql-action/upload-sarif@v3
#         if: always()
#         with:
#           sarif_file: 'trivy-results.sarif'

#       - name: Analyze vulnerability scan results
#         id: vuln-check
#         run: |
#           echo "Analyzing Trivy vulnerability scan results..."
          
#           if [ -f "trivy-results.sarif" ]; then
#             echo "Trivy SARIF file found, parsing results..."
            
#             total_vulnerabilities=$(jq '[.runs[].results[]] | length' trivy-results.sarif 2>/dev/null || echo "0")
            
#             echo "Critical/High vulnerabilities found: $total_vulnerabilities"
#             echo "vulnerability_count=$total_vulnerabilities" >> $GITHUB_OUTPUT
            
#             if [ "$total_vulnerabilities" -gt 0 ]; then
#               echo "SECURITY BLOCK: Critical or high severity vulnerabilities detected!"
#               echo "Deployment will be blocked for security reasons"
#               echo "Total vulnerabilities: $total_vulnerabilities"
              
#               echo "Sample vulnerabilities:"
#               jq -r '.runs[].results[0:3][] | "- " + (.ruleId // "Unknown") + ": " + .message.text' trivy-results.sarif 2>/dev/null || echo "Could not parse vulnerability details"
              
#               echo "deployment_blocked=true" >> $GITHUB_OUTPUT
#               exit 1
#             else
#               echo "SECURITY PASSED: No critical or high severity vulnerabilities found"
#               echo "Image is safe for deployment"
#               echo "deployment_blocked=false" >> $GITHUB_OUTPUT
#             fi
#           else
#             echo "Trivy SARIF file not found - scan may have failed"
#             echo "Proceeding with caution (scanner unavailable)"
#             echo "deployment_blocked=false" >> $GITHUB_OUTPUT
#           fi

#       # Шаг 2: Финальная мультиплатформенная сборка и публикация
#       - name: Build and push multi-platform Docker image
#         if: |
#           success() && 
#           steps.vuln-check.outputs.deployment_blocked == 'false' &&
#           github.event_name == 'push' &&
#           github.ref == 'refs/heads/main'
#         uses: docker/build-push-action@v5
#         with:
#           context: .
#           file: build/Dockerfile
#           platforms: linux/amd64,linux/arm64  # Мультиплатформенная сборка
#           secrets: |
#             api_key=${{ secrets.WEATHER_API_KEY }}
#           tags: ${{ steps.meta.outputs.tags }}
#           labels: ${{ steps.meta.outputs.labels }}
#           # cache-from: |
#           #   type=registry,ref=${{ env.DOCKERHUB_CACHE_IMAGE }}:latest
#           # cache-to: |
#           #   type=registry,ref=${{ env.DOCKERHUB_CACHE_IMAGE }}:latest,mode=max
#           push: true  # Публикуем напрямую в registry
#           sbom: true
#           provenance: mode=max

name: Build and Push Docker Image

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  DOCKERHUB_CACHE_IMAGE: dalvy07/weather-app-cache

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup QEMU for multi-platform builds
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub (for cache)
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=sha,format=long

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: build/Dockerfile
          platforms: linux/amd64,linux/arm64
          secrets: |
            api_key=${{ secrets.WEATHER_API_KEY }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: |
            type=registry,ref=${{ env.DOCKERHUB_CACHE_IMAGE }}:latest
          cache-to: |
            type=registry,ref=${{ env.DOCKERHUB_CACHE_IMAGE }}:latest,mode=max
          push: true
      
      - name: Run Trivy scan for critical vulnerabilities
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ghcr.io/dalvy07/MinimalWeatherGoAppWithActions:${{ github.sha }}
          format: 'table'
          severity: 'CRITICAL,HIGH'
          exit-code: '1' # Прерывает выполнение при обнаружении критических уязвимостей